ARG APP_CONTAINER=pytorch
ARG VER_CONTAINER=25.08-py3
FROM nvcr.io/nvidia/$APP_CONTAINER:$VER_CONTAINER

# EXPOSE 8888/tcp
# ENTRYPOINT ["jupyter-lab"]
# CMD ["--no-browser", "--ip=0.0.0.0"]

USER root
WORKDIR /tmp/

RUN python -m pip --no-cache-dir install jupyterhub && \
    jupyter --version && \
    jupyterhub --version

EXPOSE 8888/tcp
ENTRYPOINT ["jupyterhub-singleuser"]
CMD [""]

RUN useradd --create-home --no-user-group jovyan
VOLUME /home/jovyan/work
USER jovyan
WORKDIR /home/jovyan/
