ARG ROOT_CONTAINER=rlinfati/jupyter-lab0:julia-999
FROM $ROOT_CONTAINER

RUN julia --threads auto --eval "using InteractiveUtils; versioninfo(); @ccall jl_dump_host_cpu()::Cvoid"

RUN julia --threads auto <<EOF
    import Pkg
    Pkg.add("CUDA")
    import CUDA
    CUDA.set_runtime_version!(v"12.2")
EOF

RUN julia --threads auto <<EOF
    import CUDA
    CUDA.precompile_runtime()
EOF
