ARG VER_CONTAINER=julia
FROM rlinfati/jupyter-lab0:$VER_CONTAINER

RUN julia --threads auto --eval "using InteractiveUtils; versioninfo(); @ccall jl_dump_host_cpu()::Cvoid"

RUN julia --threads auto <<EOF
    import Pkg
    Pkg.add("CUDA")
    import CUDA
    CUDA.set_runtime_version!(v"12.2")
EOF
# FIX v12.2

RUN julia --threads auto <<EOF
    import CUDA
    CUDA.precompile_runtime()
EOF
