apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-sa
  namespace: jupyterhub-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-role
  namespace: jupyterhub-k8s
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-rolebinding
  namespace: jupyterhub-k8s
subjects:
  - kind: ServiceAccount
    name: jupyterhub-sa
    namespace: jupyterhub-k8s
roleRef:
  kind: Role
  name: jupyterhub-role
  apiGroup: rbac.authorization.k8s.io
