apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-www
  namespace: jupyterhub-k8s
spec:
  selector:
    app: jupyterhub-label
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-api
  namespace: jupyterhub-k8s
spec:
  selector:
    app: jupyterhub-label
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
