name: Julia 1.10
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Julia JHUB]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.JULIA
          secrets: |
            "GUROBIWLS=${{ secrets.GUROBIWLS }}"
          build-args: |
            JULIA_VERSION=1.10
          tags: rlinfati/jupyter-lab0:julia-110
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.CUDAlab
          build-args: |
            ROOT_CONTAINER=rlinfati/jupyter-lab0:julia-110
          tags: rlinfati/jupyter-lab0:cudalab-110
