name: Julia JHUB
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.HUB
          tags: rlinfati/jupyter-lab0:hub-999
      - uses: docker/build-push-action@v5
        with:
          file: Dockerfile.ORlib
          build-args: |
            JULIA_VERSION=nightly
          secrets: |
            "GUROBIWLS=${{ secrets.GUROBIWLS }}"
