name: Jupyter Nvidia
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvidia:
          - app: pytorch
            ver: 25.06-py3
          - app: tensorflow
            ver: 25.02-tf2-py3
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          tool-cache: true
          swap-storage: true
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Dockerfile.NVIDIA
      - uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.NVIDIA
          build-args: |
            APP_CONTAINER=${{ matrix.nvidia.app }}
            VER_CONTAINER=${{ matrix.nvidia.ver }}
          tags: rlinfati/jupyter-lab0:NV${{ matrix.nvidia.app }} 
